from django.urls import path
# from.http import views
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('student_home/', views.indexstudent, name='student_home'),
    path('teacher_home/', views.indexteacher, name='teacher_home'),
    path('admin_index/', views.admin_index, name='admin_index'),
    path('insert_data/', views.insert_data, name='insert_data'),
    #path('view_table/', view_table, name='table'),
    path('students_reg/', views.students_reg , name='students_reg'),
    path('view_teacher/', views.view_teacher, name='view_teacher'),
    path('view_students/', views.view_students, name='view_students'),
    path('edit_student/<str:admissionno>/', views.edit_student, name='edit_student'),
    path('delete_student/<str:admissionno>/', views.delete_student, name='delete_student'),
    path('edit_teacher/<str:teachid>/', views.edit_teacher, name='edit_teacher'),
    path('delete_teacher/<str:teachid>/', views.delete_teacher, name='delete_teacher'),
    path('add_notification/', views.add_notification, name='add_notification'),
    path('view_notification/', views.view_notification, name='view_notification'),
    path('search_students/', views.search_students, name='search_students'),
    path('table_doubt/', views.table_doubt, name='table_doubt'),
    path('view_doubts/', views.view_doubts, name='view_doubts'),
    path('edit_doubt/<str:doubtid>/', views.edit_doubt, name='edit_doubt'),
    path('delete_dbt_confirm/<str:doubtid>/', views.delete_doubts, name='delete_dbt_confirm'),
    path('view_teach_doubts/', views.view_teach_doubts, name='view_teach_doubts'),
    path('insert_reply/<str:doubtid>/', views.insert_reply, name='insert_reply'),
    path('edit_reply/<str:doubtid>/', views.edit_reply, name='edit_reply'),
    path('login/<str:usertype>/', views.login_func, name='login'),
    path('edit_student_individual/', views.edit_student_individual, name='edit_student_individual'),
    path('edit_teacher_individual/', views.edit_teacher_individual, name='edit_teacher_individual'),
    path('logout/', views.logout, name='logout'),
    path('insert_attendance/<str:admissionno>/', views.insert_attendance, name='insert_attendance'),
    path('attendance_status/', views.attendance_status, name='attendance_status'),
    path('add_examination/', views.add_examination, name='add_examination'),
    path('view_examinations/', views.view_examinations, name='view_examinations'),
    path('edit_examination/<int:exam_key>/', views.edit_examination, name='edit_examination'),
    path('delete_examination/<int:exam_key>/', views.delete_examination, name='delete_examination'),
    path('exam_view/', views.exam_view, name='exam_view'),
    path('save_answer/', views.save_answer, name='save_answer'),
    path('teacher_exam_answers/<str:admissionno>/', views.teacher_exam_answers, name='teacher_exam_answers'),
    path('add_classes', views.add_classes, name='add_classes'),
    path('check_class/', views.check_class, name='check_class'),
    
]
