# Generated by Django 5.0.1 on 2024-02-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0002_studentsmod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='studentsmod',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
