# Generated by Django 5.0.1 on 2024-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0004_modelforteach'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForTeacher',
            fields=[
                ('teachid', models.AutoField(primary_key=True, serialize=False)),
                ('teachername', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableOfNotifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=70)),
                ('current_date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelForTeach',
        ),
    ]
