# Generated by Django 5.0.1 on 2024-03-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0011_alter_studentsmod_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelforteacher',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
