# Generated by Django 5.0.1 on 2024-03-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0012_modelforteacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmod',
            name='usertype',
            field=models.CharField(default='StudentsMod', max_length=100),
        ),
    ]
