# Generated by Django 5.0.1 on 2024-03-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0013_studentsmod_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelforteacher',
            name='usertype',
            field=models.CharField(default='Teacher', max_length=100),
        ),
    ]
