# Generated by Django 5.0.1 on 2024-03-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0014_modelforteacher_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmod',
            name='usertype',
            field=models.CharField(default='Student', max_length=100),
        ),
    ]
