# Generated by Django 5.0.1 on 2024-03-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0016_loginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceid', models.AutoField(primary_key=True, serialize=False)),
                ('studentsaddmissionno', models.CharField(max_length=100)),
                ('teacherid', models.CharField(max_length=100)),
                ('currentdate', models.DateField(null=True)),
                ('attendancestatus', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='studentsmod',
            name='classstud',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
