# Generated by Django 5.0.1 on 2024-03-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0017_attendance_studentsmod_classstud'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMod',
            fields=[
                ('attendanceid', models.AutoField(primary_key=True, serialize=False)),
                ('studentsaddmissionno', models.CharField(max_length=100)),
                ('teacherid', models.CharField(max_length=100)),
                ('currentdate', models.DateField(null=True)),
                ('attendancestatus', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
