# Generated by Django 5.0.1 on 2024-03-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0018_attendancemod_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemod',
            name='attendancestatus',
            field=models.CharField(max_length=11),
        ),
    ]
