# Generated by Django 5.0.1 on 2024-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0020_exammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('login_id', models.CharField(max_length=50)),
                ('current_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
