# Generated by Django 5.0.1 on 2024-03-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0023_remove_answermodel_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='answer',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
