# Generated by Django 5.0.3 on 2024-03-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0024_exammodel_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClassModel',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('dateofclass', models.DateField()),
                ('timeofclass', models.TimeField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('teacher_id', models.CharField(max_length=20)),
            ],
        ),
    ]
