# Generated by Django 5.0.3 on 2024-03-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0025_onlineclassmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclassmodel',
            name='classofstudent',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
